spring:
  application:
    name: dubbo_study-one-app
  dubbo:
    server: true
    registry: zookeeper://localhost:2181
    application:
      name: dubbo_study-one-app
    protocol:
      port: 20880
server:
  port: 8080

